"""Report generation: a decision ready case per attack chain.

"Writing the incident up takes as long as the investigation" is one of the
pains the product exists to remove (Master Specification 2.1): each triaged
chain gets a report ready narrative + remediation, assembled from

- deterministic facts from the correlation engine (timeline, entities,
  tactic sequence, risk), and
- the AI's grounded verdict (validated techniques only; every cited
  evidence field is rendered with its actual values from the raw logs).

Every AI-authored section is labelled as such, rejected/unverified claims
are shown — not hidden — and the footer names the model and timestamp so a
human reviewer knows exactly what they are reading.
"""

from __future__ import annotations

from typing import Any, Optional

from engine.ai.kb import AttackKB
from engine.ai.reasoner import TriageResult
from engine.normalize.timeutil import ms_to_iso

AI_DISCLAIMER = "Generated by AI. Human review is required."


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def technique_label(uid: str, kb: Optional[AttackKB]) -> str:
    record = kb.get(uid) if kb is not None else None
    if record is None:
        return uid
    tactics = f" ({', '.join(record.tactics)})" if record.tactics else ""
    return f"{uid} {record.name}{tactics}"


def build_report(
    summary: dict[str, Any],
    triage: Optional[TriageResult],
    *,
    kb: Optional[AttackKB] = None,
    dashboard_url: str = "",
) -> str:
    """Markdown case report for one attack chain.

    ``summary`` is CorrelationEngine.cluster_summary() output. ``triage`` is
    None when the AI layer was unavailable — the report then carries the
    deterministic sections plus an honest pending note, never a fabricated
    verdict.
    """
    cluster_id = summary["cluster_id"]
    lines: list[str] = [f"# Attack Chain {cluster_id}", ""]

    if triage is not None:
        validation = triage.validation
        lines += [
            f"**Verdict:** {triage.verdict.verdict}  ",
            f"**Confidence:** {validation.final_confidence}/100"
            + (f" (model reported {validation.original_confidence}, "
               f"adjusted by the grounding validator)"
               if validation.final_confidence != validation.original_confidence
               else ""),
        ]
    else:
        lines += ["**Verdict:** pending. AI triage was not available for this "
                  "run; correlation results are shown below."]
    lines += [
        "",
        f"**Deterministic disposition:** {summary['disposition']}  ",
        f"**Cumulative entity risk:** {summary['risk_score']}"
        f" ({'surfaced' if summary['surfaced'] else 'below threshold'})  ",
        f"**Window (UTC):** {ms_to_iso(summary['first_time'])} to "
        f"{ms_to_iso(summary['last_time'])}  ",
        f"**Primary entity:** {summary['primary_entity']}",
    ]
    if dashboard_url:
        lines += ["", f"[View attack chain]({dashboard_url})"]

    # -- deterministic timeline ------------------------------------------------
    lines += [
        "",
        "## Timeline",
        "",
        "| Time (UTC) | Alert | Severity | Entities |",
        "|---|---|---|---|",
    ]
    for alert in summary["alerts"]:
        lines.append(
            f"| {alert['time_dt']} | {_md_escape(alert['title'])} "
            f"| {alert['severity']} "
            f"| {_md_escape(', '.join(alert['entities']))} |"
        )
    if summary.get("tactic_sequence"):
        lines += [
            "",
            "**Tactic progression:** "
            + " → ".join(summary["tactic_sequence"]),
        ]

    if triage is None:
        lines += ["", "---", "_This report contains correlation data only. AI triage is pending._"]
        return "\n".join(lines)

    verdict = triage.verdict
    validation = triage.validation

    # -- MITRE mapping (validated against the RAG payload) ---------------------
    lines += ["", "## MITRE ATT&CK techniques", ""]
    if validation.valid_techniques:
        for uid in validation.valid_techniques:
            lines.append(f"- {technique_label(uid, kb)}")
    else:
        lines.append("- none confirmed against the retrieved candidates")
    if validation.rejected_techniques:
        lines += [
            "",
            "> Rejected by the grounding validator (not present in the "
            "retrieved ATT&CK candidates): "
            + ", ".join(validation.rejected_techniques),
        ]

    # -- AI analysis (labelled) -------------------------------------------------
    lines += [
        "",
        f"## Analysis ({AI_DISCLAIMER})",
        "",
        "**Benign hypothesis.** " + verdict.benign_hypothesis,
        "",
        "**Malicious hypothesis.** " + verdict.malicious_hypothesis,
        "",
        "**Investigation.** " + verdict.investigation_chain_of_thought,
    ]

    # -- cited evidence, rendered with real values ------------------------------
    lines += ["", "## Cited evidence", ""]
    if validation.verified_fields:
        for field_key in validation.verified_fields:
            occurrences = triage.payload.field_values.get(field_key, [])
            rendered = "; ".join(
                f"`{alert_uid}` → {value}" for alert_uid, value in occurrences
            )
            lines.append(f"- **{field_key}**: {rendered or '(value elided)'}")
    else:
        lines.append("- no evidence fields were verifiably cited")
    if validation.unverified_fields:
        lines += [
            "",
            "> Cited but NOT found in the raw logs (confidence capped): "
            + ", ".join(validation.unverified_fields),
        ]

    if verdict.missing_context:
        lines += ["", "## Missing context", ""]
        lines += [f"- {item}" for item in verdict.missing_context]

    if verdict.remediation_recommendations:
        lines += ["", "## Recommended remediation", ""]
        lines += [f"- {item}" for item in verdict.remediation_recommendations]
        lines += ["", "_Recommendations only. LogLookup never executes "
                  "response actions._"]

    lines += [
        "",
        "---",
        f"_{AI_DISCLAIMER} Model: {triage.model_id} "
        f"(provider: {triage.provider}). Generated: {triage.generated_at}._",
    ]
    return "\n".join(lines)
